---
title: Hello World!
author: Andrew Moskowitz
date: '2019-08-11'
slug: hello-world
categories:
  - Website
  - R
tags:
  - Website
  - R
  - Rmarkdown
  - Blogdown
subtitle: 'A brief introduction and mission statement'
summary: ''
authors: []
lastmod: '2019-08-11T20:56:08-07:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

## Hello World!

Thanks for visiting! For a long time I've thought about creating a place among the millions of others on the internet where I can kick around some ideas and develop projects for personal enrichment.Finally I've completed step 1! The topics I hope to cover in this blog will revolve around the infinite topics that make up data science and one day, when I finally get up the nerve to push a comment section, serve as a place of discussion for some of the less explored aspects of data analysis and statistics from both a self-taught and academic perspective. 

For some context, I feel it's prudent to tell you a bit about me. In 2017, I finished my PhD in Quantitative Psychology from UCLA. During my last few years in the program, I took stock of the academic world from my (limited) perspective and decided it was no longer a professional path I wanted to pursue for several reasons: 1. I didn't like the concept of not having control over where I lived. In academia, you often need to go where the jobs are and considering I did not consider myself an extraordinary researcher (reason #2) I wasn't going to have the luxury of picking my institution. While industry positions require you to go where the work is as well, there is considerably more opportunity in areas that I find it desirable to live. 2. I wasn't that great at research. I still find this pretty hard to admit, but I was never going to be one of the great researchers to push the field forward. Where I do think I excel, is understanding applied problems and being able to translate problems into analytically tractable solutions and back again. This is an area where I could be useful in industry. 3. I have a strong conviction that the academic business model is due for a major overhaul in my working lifetime. Degrees are getting more and more expensive and the high paying jobs to justify the cost are simply not as abundant. Although I think (read: hope) whatever change occurs will ultimately be a good thing for society, I didn't want to be in the middle of it as a professional.

After coming to the realization that I was not long for the Academic world, I had to figure out how I could parlay my quantitative skills into something that would be palatable and applicable to industry. As I looked around at my mentors from academia, I realized that none of them had ever stepped out of the ivory tower and if they did it was in a capacity closely related to their expertise and mostly entrepreneurial. No one could give me guidance and help me to build the skills I needed that would help me break into the workforce. What was worse was that I didn't even know where to begin. "You don't know what you don't know" as they say. As a result, I'm hoping to dive deep in some future posts on what graduate students should learn **and highlight on their resumes** to break into industry. A few examples include dev-ops, SQL and data modeling, data collection, and breaking down cases/work-streams. 

Having managed a Data Science team for a few years now and interviewed and hired a number of analytics professionals I've also seen the other side of the world. Analysts/Data Scientists who develop on the job or through boot camps. There is nothing more valuable in the professional world as having done the job you're trying to do before and developing on the job is a great path for anyone. That said, it is easy for people on this path to miss out on some of the know how that you gain from a highly focused post graduate education. Some of these skills (i.e., intermediate to advanced statistical methods) are often NOT taught in boot camps or on the job because they tend to be more specialized and fall outside of the limited curriculum of boot camps and many managers may be unaware of other methods utility. These advanced methods (outside of the typical machine learning approaches) and how they can apply to certain problems will be another on-going topic of this blog. For instance, I've recently been reading up on Bayesian methods and identifying areas where they may help to improve tests in marketing and other applications. 

If you've read this far, I truly appreciate your interest and hope that you come along this ride with me. Check back periodically as I'll be doing analyses, writing how-tos, and pontificating on topics I hope you find interesting. If you don't see something for a long while, feel free to drop me a line- accountability is one of the reasons I started this blog. Finally, if you'd like to chat or have an idea for a project we can collaborate feel free to reach out. I'd love to connect and explore what we could do together. 

-ALM

```{r echo=FALSE}

```



